"""Initial migration

Revision ID: 6e8a9c0934fb
Revises: 
Create Date: 2026-08-07 14:00:40.345614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8a9c0934fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_lifecycle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=100), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('trade_quality', sa.String(length=10), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit_1', sa.Float(), nullable=True),
    sa.Column('take_profit_2', sa.Float(), nullable=True),
    sa.Column('take_profit_3', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('expected_move', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('market_trend', sa.String(length=50), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('supporting_indicators', sa.JSON(), nullable=True),
    sa.Column('ai_models_used', sa.JSON(), nullable=True),
    sa.Column('consensus_pct', sa.Float(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('execution_status', sa.String(length=50), nullable=True),
    sa.Column('paper_trade_id', sa.String(length=100), nullable=True),
    sa.Column('historical_accuracy', sa.Float(), nullable=True),
    sa.Column('win_probability', sa.Float(), nullable=True),
    sa.Column('similar_trades', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_holding_time', sa.Float(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_lifecycle_asset'), 'signal_lifecycle', ['asset'], unique=False)
    op.create_index(op.f('ix_signal_lifecycle_created_at'), 'signal_lifecycle', ['created_at'], unique=False)
    op.create_index(op.f('ix_signal_lifecycle_signal_id'), 'signal_lifecycle', ['signal_id'], unique=True)
    op.create_index(op.f('ix_signal_lifecycle_status'), 'signal_lifecycle', ['status'], unique=False)
    op.create_index(op.f('ix_signal_lifecycle_timeframe'), 'signal_lifecycle', ['timeframe'], unique=False)
    op.drop_index(op.f('idx_decision_history_request'), table_name='decision_history')
    op.drop_index(op.f('idx_journal_strategy'), table_name='journal_trades')
    op.drop_index(op.f('idx_journal_symbol'), table_name='journal_trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_journal_symbol'), 'journal_trades', ['symbol'], unique=False)
    op.create_index(op.f('idx_journal_strategy'), 'journal_trades', ['strategy_used'], unique=False)
    op.create_index(op.f('idx_decision_history_request'), 'decision_history', ['request_id'], unique=False)
    op.drop_index(op.f('ix_signal_lifecycle_timeframe'), table_name='signal_lifecycle')
    op.drop_index(op.f('ix_signal_lifecycle_status'), table_name='signal_lifecycle')
    op.drop_index(op.f('ix_signal_lifecycle_signal_id'), table_name='signal_lifecycle')
    op.drop_index(op.f('ix_signal_lifecycle_created_at'), table_name='signal_lifecycle')
    op.drop_index(op.f('ix_signal_lifecycle_asset'), table_name='signal_lifecycle')
    op.drop_table('signal_lifecycle')
    # ### end Alembic commands ###
