"""Phase 33 and 35 updates

Revision ID: ac902b60061b
Revises: 7f7d82f36e78
Create Date: 2026-08-19 22:09:28.437493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac902b60061b'
down_revision: Union[str, Sequence[str], None] = '7f7d82f36e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_orders', sa.Column('take_profit', sa.Float(), nullable=True))
    op.add_column('paper_orders', sa.Column('stop_loss', sa.Float(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('trace_id', sa.String(length=36), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('duplicate_protection_hash', sa.String(length=64), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('candle_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('data_age_seconds', sa.Float(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('data_freshness_status', sa.String(length=20), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('signal_state', sa.String(length=30), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('model_trace', sa.JSON(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('intelligence_snapshot', sa.JSON(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('outcome', sa.String(length=20), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('exit_price', sa.Float(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('gross_pnl', sa.Float(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('spread_cost', sa.Float(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('slippage_cost', sa.Float(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('fees_cost', sa.Float(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('net_pnl', sa.Float(), nullable=True))
    op.add_column('signal_lifecycle', sa.Column('r_multiple', sa.Float(), nullable=True))
    op.create_index(op.f('ix_signal_lifecycle_duplicate_protection_hash'), 'signal_lifecycle', ['duplicate_protection_hash'], unique=True)
    op.create_index(op.f('ix_signal_lifecycle_signal_state'), 'signal_lifecycle', ['signal_state'], unique=False)
    op.create_index(op.f('ix_signal_lifecycle_trace_id'), 'signal_lifecycle', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_lifecycle_trace_id'), table_name='signal_lifecycle')
    op.drop_index(op.f('ix_signal_lifecycle_signal_state'), table_name='signal_lifecycle')
    op.drop_index(op.f('ix_signal_lifecycle_duplicate_protection_hash'), table_name='signal_lifecycle')
    op.drop_column('signal_lifecycle', 'r_multiple')
    op.drop_column('signal_lifecycle', 'net_pnl')
    op.drop_column('signal_lifecycle', 'fees_cost')
    op.drop_column('signal_lifecycle', 'slippage_cost')
    op.drop_column('signal_lifecycle', 'spread_cost')
    op.drop_column('signal_lifecycle', 'gross_pnl')
    op.drop_column('signal_lifecycle', 'exit_time')
    op.drop_column('signal_lifecycle', 'exit_price')
    op.drop_column('signal_lifecycle', 'outcome')
    op.drop_column('signal_lifecycle', 'intelligence_snapshot')
    op.drop_column('signal_lifecycle', 'model_trace')
    op.drop_column('signal_lifecycle', 'signal_state')
    op.drop_column('signal_lifecycle', 'data_freshness_status')
    op.drop_column('signal_lifecycle', 'data_age_seconds')
    op.drop_column('signal_lifecycle', 'prediction_timestamp')
    op.drop_column('signal_lifecycle', 'candle_timestamp')
    op.drop_column('signal_lifecycle', 'duplicate_protection_hash')
    op.drop_column('signal_lifecycle', 'trace_id')
    op.drop_column('paper_orders', 'stop_loss')
    op.drop_column('paper_orders', 'take_profit')
    # ### end Alembic commands ###
