import json
from fastapi.openapi.utils import get_openapi
from app.main import app

def generate_docs():
    """
    Generate markdown documentation from the FastAPI schema.
    """
    schema = get_openapi(
        title=app.title,
        version=app.version,
        openapi_version=app.openapi_version,
        description=app.description,
        routes=app.routes,
    )
    
    with open("docs.md", "w") as f:
        f.write("# TradeSignalAI-v3 API Documentation\n\n")
        f.write("This document is auto-generated by the Documentation Generator.\n\n")
        
        for path, methods in schema.get("paths", {}).items():
            f.write(f"## Path: `{path}`\n")
            for method, details in methods.items():
                f.write(f"### {method.upper()}\n")
                f.write(f"**Summary**: {details.get('summary', 'No summary')}\n\n")
                f.write(f"**Description**: {details.get('description', 'No description')}\n\n")
                f.write("---\n")
                
    print("Generated docs.md successfully.")

if __name__ == "__main__":
    generate_docs()
