"""
Internal Position Manager — Source of Truth for Portfolio State

This module maintains the authoritative record of positions generated by the
paper trading execution system. The reconciliation engine compares this against
broker/paper state to detect divergences.

Key invariants:
- Position quantity + average_entry_price are immutable once set
- Position changes are atomic (append-only trade log)
- Position retrieval is always consistent with trade log
- Restart/resume recovers state from persistence
"""
from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

from app.logs.logger import get_logger
from app.execution.types import Position, Order, OrderSide, OrderStatus

logger = get_logger(__name__)


@dataclass
class PositionRecord:
    """Immutable position snapshot at a point in time."""
    symbol: str
    quantity: float  # Positive = long, Negative = short
    average_entry_price: float
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    # Audit trail
    entry_trade_id: str | None = None
    last_update_trade_id: str | None = None


@dataclass
class TradeRecord:
    """Immutable trade record for audit trail and position reconstruction."""
    id: str  # Trade ID (UUID)
    order_id: str  # Order ID at time of execution
    symbol: str
    side: OrderSide
    price: float
    quantity: float
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    fee: float = 0.0
    realized_pnl: float = 0.0
    counter_party: str = "paper_executor"
    # Metadata for traceability
    generation_version: str = "v3.33.0"  # Strategy version


class PositionManager:
    """
    Manages internal positions with full audit trail.
    
    This is the single source of truth for portfolio state after execution.
    The reconciliation engine compares this against broker/paper state.
    """

    _instance = None
    _lock = asyncio.Lock()

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance._positions: dict[str, PositionRecord] = {}
            cls._instance._trade_log: list[TradeRecord] = []
            cls._instance._orders: dict[str, Order] = {}  # Order ID -> Order
            cls._instance._order_to_trade: dict[str, str] = {}  # Order ID -> Trade ID
            cls._instance._initialized = False
        return cls._instance

    async def initialize(self):
        """Async initialization (for future persistence loading)."""
        async with self._lock:
            if self._initialized:
                return
            self._initialized = True
            logger.info("PositionManager initialized")

    # ── Order Registration ────────────────────────────────────────────────────

    def register_order(self, order: Order) -> None:
        """Register an order for tracking. Must be called before order is submitted."""
        self._orders[order.id] = order

    async def record_trade(self, trade_record: TradeRecord) -> None:
        """Append a completed trade to the audit log and update positions."""
        async with self._lock:
            # Add to trade log
            self._trade_log.append(trade_record)
            
            # Map order -> trade
            if trade_record.order_id in self._orders:
                self._order_to_trade[trade_record.order_id] = trade_record.id
            
            # Update position
            symbol = trade_record.symbol
            if symbol not in self._positions:
                # New position
                self._positions[symbol] = PositionRecord(
                    symbol=symbol,
                    quantity=trade_record.quantity,
                    average_entry_price=trade_record.price,
                    timestamp=trade_record.timestamp,
                    entry_trade_id=trade_record.id,
                    last_update_trade_id=trade_record.id
                )
            else:
                # Existing position - apply trade
                pos = self._positions[symbol]
                old_qty = pos.quantity
                old_avg = pos.average_entry_price
                new_qty = old_qty + trade_record.quantity
                
                if new_qty == 0:
                    # Position closed
                    del self._positions[symbol]
                    logger.info(f"Position closed for {symbol} via trade {trade_record.id}")
                else:
                    # Position updated (flip or adjust)
                    pos.quantity = new_qty
                    if old_qty == 0 or (old_qty > 0 and new_qty < 0) or (old_qty < 0 and new_qty > 0):
                        # Flip or new position - use trade price as new avg
                        pos.average_entry_price = abs(trade_record.price)
                    else:
                        # Scale position - use weighted average
                        total_cost = abs(old_qty) * old_avg + abs(trade_record.quantity) * abs(trade_record.price)
                        pos.average_entry_price = total_cost / abs(new_qty)
                    pos.last_update_trade_id = trade_record.id
                    pos.timestamp = trade_record.timestamp

            logger.debug(f"Trade recorded: {trade_record.id} -> {symbol} {trade_record.side} {trade_record.quantity}")

    # ── Position Queries ──────────────────────────────────────────────────────

    def get_position(self, symbol: str) -> Position:
        """Get current position for a symbol. Zero position if none."""
        pos = self._positions.get(symbol.upper())
        if pos:
            return Position(
                symbol=pos.symbol,
                quantity=pos.quantity,
                average_entry_price=pos.average_entry_price,
                unrealized_pnl=0.0  # Computed by caller from current price
            )
        return Position(symbol=symbol.upper(), quantity=0.0, average_entry_price=0.0)

    def get_all_positions(self) -> dict[str, Position]:
        """Get all current positions."""
        result = {}
        for symbol, pos in self._positions.items():
            result[symbol] = Position(
                symbol=pos.symbol,
                quantity=pos.quantity,
                average_entry_price=pos.average_entry_price,
                unrealized_pnl=0.0
            )
        return result

    def get_order(self, order_id: str) -> Order | None:
        """Get order by ID."""
        return self._orders.get(order_id)

    def get_trade(self, trade_id: str) -> TradeRecord | None:
        """Get trade by ID."""
        for trade in self._trade_log:
            if trade.id == trade_id:
                return trade
        return None

    # ── Balance Tracking ──────────────────────────────────────────────────────

    def __init__(self):
        """Initialize position manager with default state."""
        self._positions: dict[str, PositionRecord] = {}
        self._trade_log: list[TradeRecord] = []
        self._orders: dict[str, Order] = {}
        self._order_to_trade: dict[str, str] = {}
        self._initialized = False
        self._balance: float = 100000.0  # Initial balance
        self._equity: float = 100000.0  # Balance + unrealized pnl
        self._realized_pnl: float = 0.0
        self._total_trades: int = 0

    @property
    def balance(self) -> float:
        return self._balance

    @property
    def equity(self) -> float:
        return self._equity

    @property
    def realized_pnl(self) -> float:
        return self._realized_pnl

    @property
    def total_trades(self) -> int:
        return self._total_trades


# Global singleton instance
position_manager = PositionManager()


# ── Reconciliation Integration ────────────────────────────────────────────

async def get_internal_positions_for_reconciliation() -> list[dict[str, Any]]:
    """Format positions for reconciliation comparison."""
    positions = position_manager.get_all_positions()
    result = []
    for symbol, pos in positions.items():
        result.append({
            "symbol": symbol,
            "quantity": pos.quantity,
            "average_entry_price": pos.average_entry_price,
            "unrealized_pnl": pos.unrealized_pnl,
            "status": "ACTIVE",
            "source": "internal"
        })
    return result